<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.3" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lancamentos.Application\Lancamentos.Application.csproj" />
    <ProjectReference Include="..\Lancamentos.Infrastructure\Lancamentos.Infrastructure.csproj" />
    <ProjectReference Include="..\..\ConsolidadoDiario\ConsolidadoDiario.Application\ConsolidadoDiario.Application.csproj" />
    <ProjectReference Include="..\..\ConsolidadoDiario\ConsolidadoDiario.Infrastructure\ConsolidadoDiario.Infrastructure.csproj" />
  </ItemGroup>
</Project>
